# Generated by Django 5.2.4 on 2025-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_address_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('delivered', 'Yetkazib berilgan')], default='active', max_length=20),
        ),
    ]
