# Generated by Django 5.2.4 on 2025-07-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
        ('users', '0005_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bot_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('delivered', 'Yetkazib berilgan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_groups', to='users.botuser')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.ordergroup'),
            preserve_default=False,
        ),
    ]
