# Generated by Django 5.2.4 on 2025-07-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
