# Generated by Django 5.2.4 on 2025-07-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
